"""empty message

Revision ID: 5e46b71a26f6
Revises: aa80dddc2858
Create Date: 2022-07-09 23:33:27.964317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e46b71a26f6'
down_revision = 'aa80dddc2858'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_raw', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_raw')
    # ### end Alembic commands ###
